name = "tarot-worker"
main = "src/index.js"
compatibility_date = "2025-06-11"
account_id = "95653ecc7b4cb84d1949c5bd667af7e7"

logpush = true

[vars]
ENVIRONMENT = "production"

[env.production]
route = "tarot-worker.wfleemkuil.workers.dev"
workers_dev = false

[env.production.vars]
ENVIRONMENT = "production"

[env.production.secrets]
LLM_API_KEY = true

[env.staging]
workers_dev = true

[env.staging.vars]
ENVIRONMENT = "staging"

[env.staging.secrets]
LLM_API_KEY = true

[env.dev]
workers_dev = true
logpush = true

[env.dev.vars]
ENVIRONMENT = "development"

[env.dev.secrets]
LLM_API_KEY = true

[env.dev.ai]
enabled = true

[ai]
enabled = true